config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

    resources :posts do
        resources :comments
    end
    root "posts#index"

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
    devise :database_authenticatable,
    :recoverable, :rememberable, :trackable, :validatable

    # Setup accessible (or protected) attributes for your model
    #attr_accessible :email, :login, :password, :password_confirmation, :remember_me

    attr_accessor :login

    protected

    def self.find_for_database_authentication(warden_conditions)
        conditions = warden_conditions.dup
        login = conditions.delete(:login)
        where(conditions).where(["lower(email) = :value", { :value => login.strip.downcase }]).first
    end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
    extend FriendlyId
    friendly_id :title, use: :slugged
    has_many :comments, dependent: :destroy
    validates :title, presence: true, length: {minimum: 5}
    validates :body, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable, :authentication_keys => [:login]

  attr_accessor :login
    def self.find_first_by_auth_conditions(warden_conditions)
        conditions = warden_conditions.dup
        if login = conditions.delete(:login)
            where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
        else
            if conditions[:username].nil?
                where(conditions).first
            else
                where(username: conditions[:username]).first
            end
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
        devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :username, :email, :password, :remember_me) }
        devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password) }
    end



end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
        @post = Post.friendly.find(params[:post_id])
        @comment = @post.comments.create(params[:comment].permit(:name, :body))

        redirect_to post_path(@post)
    end
    def destroy
        @post = Post.friendly.find(params[:post_id])
        @comment = @post.comments.find(params[:id])
        @comment.destroy

        redirect_to post_path(@post)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    def index
        @posts = Post.all.order('created_at DESC')
    end

    def new
        @post = Post.new
    end

    def create
        @post = Post.new(post_params)

        if @post.save
            redirect_to @post
        else
            render 'new'
        end
    end

    def show
        @post = Post.friendly.find(params[:id])
    end

    def edit
        @post = Post.friendly.find(params[:id])
    end

    def update
        @post = Post.find(params[:id])

        if @post.update(params[:post].permit(:title, :body))
            redirect_to @post
        else
            render 'edit'
        end
    end

    def destroy
        @post = Post.friendly.find(params[:id])
        @post.destroy

        redirect_to posts_path
    end


    private

    def post_params
        params.require(:post).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div class="comment clearfix">
    <p><%= link_to 'Delete', [comment.post, comment],
method: :delete,
class: "button",
data: { confirm: 'Are you sure?' } %>
    </p>
    <div class="comment_content">
        <p class="comment_name"><strong><%= comment.name %></strong></p>
        <p class="comment_body"><%= comment.body %></p>
        <p class="comment_time"><%= time_ago_in_words(comment.created_at) %> Ago</p>
    </div>
</div>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
<%= f.label :name %><br>
<%= f.text_field :name %><br>
<br>
<%= f.label :body %><br>
<%= f.text_area :body %><br>
<br>
<%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Atussec</title>
    <%= stylesheet_link_tag 'application', 'http://fonts.googleapis.com/css?family=Raleway:400,700' %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

    <div id="sidebar">
        <div id="logo">
            <%= link_to root_path do %>
            <%= image_tag "logo.svg" %>
            <% end %>
        </div>

        <ul>
            <li class="category">Website</li>
            <li><%= link_to "Blog", root_path %></li>
            <li>About</li>
        </ul>

        <ul>
            <li class="category">Social</li>
            <li><a href="https://twitter.com/atussec">Twitter</a></li>
            <li><a href="http://instagram.com/atussec">Instagram</a></li>

            <li><a href="mailto:kanyi@gcubed.gm">Email</a></li>
        </ul>

        <p class="sign_in">Admin Login</p>
    </div>

    <div id="main_content">
        <div id="header">
            <p>All Posts</p>

            <div class="buttons">
                <button class="button"><%= link_to "New Post", new_post_path %></button>
                <button class="button">Log Out</button>
            </div>
        </div>
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
        <% flash.each do |name, msg| %>
        <%= content_tag(:div, msg, class: "alert") %>
        <% end %>
<%= yield %>
    </div>
</body>
</html>

app/views/posts/_form.html.erb
<%= form_for :post, url: posts_path do |f| %>

<% if @post.errors.any? %>
<div id="errors">
    <h2><%= pluralize(@post.errors.count, "error") %> prevented this post from saving:</h2>
    <ul>
        <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
    </ul>
</div>
<% end %>

<%= f.label :title %><br>
<%= f.text_field :title %><br>
<br>
<%= f.label :body %><br>
<%= f.text_field :body %><br>
<br>
<%= f.submit %>
<% end %>

app/views/posts/edit.html.erb
<div id="page_wrapper">
    <h1>Edit Post</h1>

    <%= render 'form' %>
</div>

app/views/posts/index.html.erb
<h1>This is the placeholder for index.html.erb</h1>
<% @posts.each do |post| %>
<div class="post_wrapper">
    <h2 class="title"><%= link_to post.title, post %></h2>
    <p class="date"><%= post.created_at.strftime("%B %d, %Y") %></p>
</div>
<% end %>

app/views/posts/new.html.erb
<div id="page_wrapper">
    <h1>New Post</h1>

    <%= render 'form' %>
</div>

app/views/posts/show.html.erb
<div id="post_content">
    <h1 class="title">
        <%= @post.title %>
    </h1>
    <p class="date">
        Submitted <%= time_ago_in_words(@post.created_at) %> Ago
        | <%= link_to 'Edit', edit_post_path(@post) %> |
        <%= link_to 'Delete', post_path(@post), method: :delete, data: { confirm: 'Are you sure?' } %>
    </p>
    <p class="body">
        <%= @post.body %>
    </p>
    <div id="comments">
        <h2><%= @post.comments.count %> Comments</h2>
        <%= render @post.comments %>

        <h3>Add a comment:</h3>
        <%= render "comments/form" %>
    </div>

</div>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>